# Generated by Django 3.1.3 on 2022-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listazadan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='status',
            field=models.CharField(choices=[('U', 'Undone'), ('D', 'Done')], default='U', max_length=1),
        ),
    ]
